export const data = [
  {
    customer: "AETHANOL",
    points: "",
    price: "+100",
    beatLine: 0,
    totalBets: 5,
    percentage: 50,
    win_loss: "-376.0",
    fullAnalysis: "view",
  },
  {
    customer: "BETSPORTS",
    points: "",
    price: "+150",
    beatLine: 1,
    totalBets: 8,
    percentage: 62.5,
    win_loss: "225.5",
    fullAnalysis: "view",
  },
  {
    customer: "SPORTSBET",
    points: "",
    price: "-110",
    beatLine: -2,
    totalBets: 12,
    percentage: 41.7,
    win_loss: "-85.25",
    fullAnalysis: "view",
  },
  {
    customer: "GAMBLEGURU",
    points: "",
    price: "+220",
    beatLine: 3,
    totalBets: 4,
    percentage: 75,
    win_loss: "+440.0",
    fullAnalysis: "view",
  },
  {
    customer: "BETMAKER",
    points: "",
    price: "+130",
    beatLine: -1,
    totalBets: 10,
    percentage: 50,
    win_loss: "-30.0",
    fullAnalysis: "view",
  },
  {
    customer: "WINNERBETS",
    points: "",
    price: "-120",
    beatLine: 2,
    totalBets: 6,
    percentage: 66.7,
    win_loss: "+120.75",
    fullAnalysis: "view",
  },
  {
    customer: "BETMASTER",
    points: "",
    price: "+180",
    beatLine: -3,
    totalBets: 3,
    percentage: 33.3,
    win_loss: "-180.0",
    fullAnalysis: "view",
  },
  {
    customer: "AETHANOL",
    points: "",
    price: "+100",
    beatLine: 0,
    totalBets: 5,
    percentage: 50,
    win_loss: "-376.0",
    fullAnalysis: "view",
  },
  {
    customer: "BETSPORTS",
    points: "",
    price: "+150",
    beatLine: 1,
    totalBets: 8,
    percentage: 62.5,
    win_loss: "225.5",
    fullAnalysis: "view",
  },
  {
    customer: "SPORTSBET",
    points: "",
    price: "-110",
    beatLine: -2,
    totalBets: 12,
    percentage: 41.7,
    win_loss: "-85.25",
    fullAnalysis: "view",
  },
  {
    customer: "GAMBLEGURU",
    points: "",
    price: "+220",
    beatLine: 3,
    totalBets: 4,
    percentage: 75,
    win_loss: "440.0",
    fullAnalysis: "view",
  },
  {
    customer: "BETMAKER",
    points: "",
    price: "+130",
    beatLine: -1,
    totalBets: 10,
    percentage: 50,
    win_loss: "-30.0",
    fullAnalysis: "view",
  },
  {
    customer: "WINNERBETS",
    points: "",
    price: "-120",
    beatLine: 2,
    totalBets: 6,
    percentage: 66.7,
    win_loss: "+120.75",
    fullAnalysis: "view",
  },
  {
    customer: "BETMASTER",
    points: "",
    price: "+180",
    beatLine: -3,
    totalBets: 3,
    percentage: 33.3,
    win_loss: "-180.0",
    fullAnalysis: "view",
  },
];
